name: Static code analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linelint:
    name: Check that files end with line break
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Linelint
        uses: fernandrone/linelint@master
        id: linelint
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '_data/conferences/'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.YAML_LINTER_GITHUB_TOKEN }}
