name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v2

      - name: Add site minifier plugin
        run: |
            REPLACEMENT_CODE='const eleventyPluginFilesMinifier = require("@sherby/eleventy-plugin-files-minifier");\neleventyConfig.addPlugin(eleventyPluginFilesMinifier);'
            sed -i "s|\/\* CI ADDS MINIFIER PLUGIN HERE \*\/|${REPLACEMENT_CODE}|g" .eleventy.js


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Create CNAME file
        run: echo "${{ secrets.CNAME_URL }}" > ./_site/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
